name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies & setup
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc git wget curl unzip \
            libssl-dev flex bison libncurses-dev libtinfo6 \
            python3 python3-pip
          # fallback: symlink python if scripts call python2
          if ! command -v python &>/dev/null; then
            sudo ln -sf /usr/bin/python3 /usr/bin/python
          fi
          bash init_clang_13.sh

      - name: Set environment variable
        run: echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Build LPoS
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build_kernel.sh -c

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "LPoS-${{ env.LPOS_KERNEL_VERSION }}-[N10]"
          path: |
            out/LPoS*.zip

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: "LPoS Kernel ${{ env.LPOS_KERNEL_VERSION }}"
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}
          artifacts: "out/LPoS*.zip,out/KSU*.zip"
          body: "Commit SHA: ${{ github.sha }}"
