name: build and release

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true        

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        device: [beyond2, beyond1, beyond0, beyondxks, d1, d2s, d1x, d2x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up build environment
        run: |
          sudo apt update -y  
          sudo apt install libncurses5-dev -y
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb
          git clone --depth=1 https://github.com/ravindu644/proton-12.git -b main --single-branch proton
          export PATH=$PWD/proton/bin:$PATH && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb         
          
      - name: Set environment variable
        run: |
          SHA=$(git rev-parse --short ${{ github.sha }})
          echo BUILD_DATE=$(date +'%Y%m%d') >> $GITHUB_ENV
          echo BUILD_KERNEL_VERSION=CI-${{ github.event.inputs.version }}-$SHA >> $GITHUB_ENV
          
      - name: Building Kernel
        run: |
            bash build.sh -m ${{ matrix.device }} -v ${{ env.BUILD_KERNEL_VERSION }} -l ${{ github.event.inputs.llvm }} -r n

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "MencretKernel-${{ env.BUILD_KERNEL_VERSION }}-${{ matrix.device }}-stock-One-UI"
          path: "build/out/${{ matrix.device }}/zip/*"
          if-no-files-found: error
