name: build and release to Telegram
run-name: 'Release: Build ${{ github.event.inputs.version }} for S10,N10 Series'

on:
  workflow_dispatch:
    inputs:      
      version:
        description: 'Release Version'
        required: true        

env:
  BUILD_KERNEL_VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        device: [beyond2, beyond1, beyond0, beyondxks, d1, d2s, d1x, d2x]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up build environment
        run: |
          sudo apt update -y  
          sudo apt install libncurses5-dev -y
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb         
          
      - name: Set environment variable
        run: |
          SHA=$(git rev-parse --short $GITHUB_SHA)
          echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "COMMIT_SHA=$SHA" >> $GITHUB_ENV
          
      - name: Building Kernel
        run: |
          bash build.sh ${{ matrix.device }}

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "MencretKernel-${{ env.BUILD_KERNEL_VERSION }}-${{ env.BUILD_DATE }}-${{ matrix.device }}-stock-One-UI"
          path: "build/*.tar"
          if-no-files-found: error

  telegram-notification:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BUILD_KERNEL_VERSION: ${{ github.event.inputs.version }}
      BUILD_DATE: ${{ needs.build.outputs.build_date }}

    steps:
      - name: Set build date
        run: |
          echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Upload to Telegram Group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          disable_web_page_preview: false
          message: |
            🚀 <b>MencretKernel ${{ env.BUILD_KERNEL_VERSION }} For ONEUI4.X - Build Completed!</b>

            📱 <b>Supported Devices:</b> 
            - Note10 Series: 
              - d1, 
              - d1xks, 
              - d2s, 
              - d2x
            - S10 Series: 
              - beyond0lte,
              - beyond1lte, 
              - beyond2lte, 
              - beyondx

            📦 <b>Build Details:</b>
            ⚙️ <b>Version:</b> ${{ env.BUILD_KERNEL_VERSION }}
            📅 <b>Build Date:</b> ${{ env.BUILD_DATE }}
            ☠️ <b>Commit:</b> ${{ github.sha }}

            💬 <b>For Discussion:</b>
            https://t.me/PapaL3xaKernel/2

            🔗 <b>Release:</b> <a href="https://github.com/${{ github.repository }}/releases">GitHub</a>

            <b>Repository:</b> <a href="https://github.com/${{ github.repository }}">MencretKernel</a>

            <b>Commit SHA:</b> <a href="https://github.com/${{ github.repository }}/commit/${{ github.sha }}">Click here</a>

            <b>Installation Guide:</b> <a href="https://telegra.ph/MencretKernel-Installation-Guide-10-03">Click here</a>

  release:
    needs: build  # Hanya perlu build, tidak perlu telegram-notification
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Set Release Token
        id: set-token
        run: |
          if [ -n "${{ github.event.inputs.token }}" ] && [ "${{ github.event.inputs.token }}" != "" ]; then
            echo "RELEASE_TOKEN=${{ github.event.inputs.token }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TOKEN=${{ github.token }}" >> $GITHUB_ENV
          fi

      - name: Release Build Kernel
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: "MencretKernel-${{ github.event.inputs.version }}-Stock OneUI4.X"
          draft: false
          prerelease: false
          generateReleaseNotes: true
          makeLatest: true
          skipIfReleaseExists: false
          token: ${{ secrets.GITHUB_TOKEN }}  # Gunakan GITHUB_TOKEN default
          removeArtifacts: true
          artifacts: "artifacts/**/*.tar"
          body: |
            # 🚀 MencretKernel ${{ env.BUILD_KERNEL_VERSION }} For ONEUI4.X - Build Completed!
            
            # 📱 Supported Devices: 
            - Note10 Series: 
              - d1, 
              - d1xks, 
              - d2s, 
              - d2x
            - S10 Series: 
              - beyond0lte,
              - beyond1lte, 
              - beyond2lte, 
              - beyondx

            # 📦 Build Details:
            ⚙️ <b>Version:</b> ${{ env.BUILD_KERNEL_VERSION }}
            📅 <b>Build Date:</b> ${{ env.BUILD_DATE }}
            ☠️ <b>Commit:</b> ${{ github.sha }}

            # 💬 For Discussion:
            https://t.me/PapaL3xaKernel/2

            # 🔗 Release:</b> <a href="https://github.com/${{ github.repository }}/releases">GitHub</a>
            #  Installation Guide: <a href="https://telegra.ph/MencretKernel-Installation-Guide-10-03">Click here</a>

            <b>Repository:</b> <a href="https://github.com/${{ github.repository }}">MencretKernel</a>

            <b>Commit SHA:</b> <a href="https://github.com/${{ github.repository }}/commit/${{ github.sha }}">Click here</a>